# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 15:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivation', models.IntegerField(null=True)),
                ('solar_panel_years', models.IntegerField(null=True)),
                ('installed_capacity', models.IntegerField(null=True)),
                ('feed_in', models.NullBooleanField()),
                ('feed_in_kwh', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('sde_support', models.IntegerField(null=True)),
                ('monitoring', models.IntegerField(null=True)),
                ('metering_equipment', models.IntegerField(null=True)),
                ('meter_brand', models.CharField(blank=True, max_length=50)),
                ('meter_model', models.CharField(blank=True, max_length=50)),
                ('inverter_internet', models.IntegerField(null=True)),
                ('internet', models.IntegerField(null=True)),
                ('malfunction', models.NullBooleanField()),
                ('discover', models.IntegerField(null=True)),
                ('maintenance', models.IntegerField(null=True)),
                ('maintenance_costs', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('interest_monitoring', models.NullBooleanField()),
                ('participation', models.NullBooleanField()),
                ('pay_fixed', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('pay_percentage', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('pay_preference', models.IntegerField(null=True)),
                ('explanation', models.CharField(blank=True, max_length=3000)),
                ('spread_the_word', models.NullBooleanField()),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
