# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 15:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('initials', models.CharField(blank=True, max_length=20)),
                ('surname', models.CharField(blank=True, max_length=100)),
                ('email_address', models.EmailField(max_length=254, null=True)),
                ('street', models.CharField(blank=True, max_length=100)),
                ('nr', models.IntegerField(null=True)),
                ('suffix', models.CharField(blank=True, max_length=10)),
                ('zipcode', models.CharField(blank=True, max_length=8)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('keep_me_up_to_date', models.BooleanField()),
            ],
        ),
    ]
